### ISSUE TITLE
ارور در inspect

### ISSUE THREAD

**Issue by Amirrezakashipazha** [Nima-Moradi1/guess-or-kill#1]
توی component HangManWord.tsx این قسمت :
{wordToGuess.split("").map((letter, index) => (
        <span style={{ borderBottom: ".1em solid white" ,width:"30px"}} key={index}>
          <span
            style={{
              // here we say : if the guessed letter matches the correct letter , reveal it ; otherwise DON'T!
              color: "green"
            }}
          >
            {guessedLetters.includes(letter) || reveal?letter:''}
            
             {/* {letter} */}
          </span>
        </span>
      ))}
بهتره بجای visibility از render گرفتن شرطی استفاده کرد 
در حالت اول توی inspect مشخص است فقط قابل نمایش نیست ولی در این حالت کلا render نمیگیرد 
👍

**Comment by Nima-Moradi1** [comment]
خیلی مفید بود ممنون از شما حتما اصلاح میگردد
